# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acco',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': 'user'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'notice'},
        ),
    ]
