# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:26
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171203_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='acco',
            name='headimg',
            field=models.FileField(default='moren.jpg', upload_to=account.models.get_upload_to),
        ),
    ]
