# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('others', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='album',
        ),
        migrations.AddField(
            model_name='images',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to=settings.AUTH_USER_MODEL),
        ),
    ]
